var practitioners = [
  {
    _id: "5f9192b6946284e14e29e637",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.005.png",
    name: {
      first: "Daiya",
      last: "Farms",
    },
    output: "Deliciously dairy free",
    secondary_language:
      "cheddar/mozza/pepperjack style cutting board collection 'shreds'",
    company_link: "https://daiyafoods.com/",
  },
  {
    _id: "5f9192b6278ab3fb64a9ea9e",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Vegan",
    time: "Premium",
    photo: "plant_images.006.png",
    name: {
      first: "OatZarella",
      last: "",
    },
    output: "100% Vegan/ Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://oatzarella.com/cheeses",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "All",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Millenials",
    state: "Dairy replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Millenials",
    state: "Dairy replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Millenials",
    state: "Dairy replacement",
    rank: "All",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.008.png",
    name: {
      first: "Beyond Meat",
      last: "",
    },
    output: "Plant-based patties",
    secondary_language: "20G of plant protein per serving, no soy, no gluten",
    company_link: "https://www.beyondmeat.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.009.png",
    name: {
      first: "Moving",
      last: "Mountains",
    },
    output: "B12 Burger",
    secondary_language: "bite into the future",
    company_link: "https://movingmountainsfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.009.png",
    name: {
      first: "Moving",
      last: "Mountains",
    },
    output: "B12 Burger",
    secondary_language: "bite into the future",
    company_link: "https://movingmountainsfoods.com/",
  },

  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.010.png",
    name: {
      first: "Impossible Burger",
      last: "",
    },
    output: "Burger made from plants",
    secondary_language:
      "19g protein, No animal hormones or antibiotics, 0mg cholesterol",
    company_link: "https://buy.impossiblefoods.com",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.011.png",
    name: {
      first: "Sunflower Family",
      last: "",
    },
    output: "plant-based ground",
    secondary_language: "Organic Sunflower Bolognese, seasoning blend",
    company_link: "https://www.sunflowerfamily.us/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.012.png",
    name: {
      first: "Veggie Power",
      last: "",
    },
    output: "plant-based pepperoni/ vegan ",
    secondary_language:
      "real cauliflower thin pizza crust - on a thin and deliciously crispy cauliflower crust made with Violife Mozzarella Cheese",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.013.png",
    name: {
      first: "Clo Clo",
      last: "",
    },
    output: "delectably vegan",
    secondary_language:
      "Meatless pepperoni, Meatless Italian, Spicy Meatless Carribean Pizza",
    company_link: "https://clocloveganfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.013.png",
    name: {
      first: "Clo Clo",
      last: "",
    },
    output: "delectably vegan",
    secondary_language:
      "Meatless pepperoni, Meatless Italian, Spicy Meatless Carribean Pizza",
    company_link: "https://clocloveganfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.016.png",
    name: {
      first: "OHi",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Coconut Macadamia/ No Grain, Gluten, or Soy/ Almond Curnch / Super Green / Almond Dark Chocolate",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.016.png",
    name: {
      first: "OHi",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Coconut Macadamia/ No Grain, Gluten, or Soy/ Almond Curnch / Super Green / Almond Dark Chocolate",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.016.png",
    name: {
      first: "OHi",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Coconut Macadamia/ No Grain, Gluten, or Soy/ Almond Curnch / Super Green / Almond Dark Chocolate",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.015.png",
    name: {
      first: "All Y'alls Food",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Black Pepper & Sea Salt / Prickly Pear Teriyaki / Prickly Pear Chipotle",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.015.png",
    name: {
      first: "All Y'alls Food",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Black Pepper & Sea Salt / Prickly Pear Teriyaki / Prickly Pear Chipotle",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.017.png",
    name: {
      first: "Noops",
      last: "",
    },
    output: "oatmilk pudding / plant-based",
    secondary_language: "Vanilla/Caramel/Mocha/Chocolate Flavored",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.019.png",
    name: {
      first: "Kite Hill",
      last: "",
    },
    output: "dairy free",
    secondary_language:
      "plain / vanilla / peach / strawberry / blueberry almondmilk yogurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.019.png",
    name: {
      first: "Kite Hill",
      last: "",
    },
    output: "dairy free",
    secondary_language:
      "plain / vanilla / peach / strawberry / blueberry almondmilk yogurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.020.png",
    name: {
      first: "Kite Brytlife",
      last: "",
    },
    output: "plant-based yogurt",
    secondary_language:
      "plain / vanilla / blueberry lemon / tart cherry delicious, all-natural plant-based yogurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.020.png",
    name: {
      first: "Kite Brytlife",
      last: "",
    },
    output: "plant-based yogurt",
    secondary_language:
      "plain / vanilla / blueberry lemon / tart cherry delicious, all-natural plant-based yogurt",
    company_link: "",
  },
];
var practitioners = [
  {
    _id: "5f9192b6946284e14e29e637",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.005.png",
    name: {
      first: "Daiya",
      last: "Farms",
    },
    output: "Deliciously dairy free",
    secondary_language:
      "cheddar/mozza/pepperjack style cutting board collection 'shreds'",
    company_link: "https://daiyafoods.com/",
  },
  {
    _id: "5f9192b6278ab3fb64a9ea9e",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Vegan",
    time: "Premium",
    photo: "plant_images.006.png",
    name: {
      first: "OatZarella",
      last: "",
    },
    output: "100% Vegan/ Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://oatzarella.com/cheeses",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Gen Z",
    state: "Dairy replacement",
    rank: "All",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Millenials",
    state: "Dairy replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Millenials",
    state: "Dairy replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b6946284e14e29e639",
    speciality: "Millenials",
    state: "Dairy replacement",
    rank: "All",
    time: "Convenience",
    photo: "plant_images.007.png",
    name: {
      first: "100% Awesome Vevan",
      last: "",
    },
    output: "100% Vegan/Ched-Shred/Mozza Shred/Ched Melts",
    secondary_language:
      "Authentic Malt & Texture Soft, Mild,& Perfectly Creamy",
    company_link: "https://vevanfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.008.png",
    name: {
      first: "Beyond Meat",
      last: "",
    },
    output: "Plant-based patties",
    secondary_language: "20G of plant protein per serving, no soy, no gluten",
    company_link: "https://www.beyondmeat.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.009.png",
    name: {
      first: "Moving",
      last: "Mountains",
    },
    output: "B12 Burger",
    secondary_language: "bite into the future",
    company_link: "https://movingmountainsfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.009.png",
    name: {
      first: "Moving",
      last: "Mountains",
    },
    output: "B12 Burger",
    secondary_language: "bite into the future",
    company_link: "https://movingmountainsfoods.com/",
  },

  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meat - burger",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.010.png",
    name: {
      first: "Impossible Burger",
      last: "",
    },
    output: "Burger made from plants",
    secondary_language:
      "19g protein, No animal hormones or antibiotics, 0mg cholesterol",
    company_link: "https://buy.impossiblefoods.com",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.011.png",
    name: {
      first: "Sunflower Family",
      last: "",
    },
    output: "plant-based ground",
    secondary_language: "Organic Sunflower Bolognese, seasoning blend",
    company_link: "https://www.sunflowerfamily.us/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.012.png",
    name: {
      first: "Veggie Power",
      last: "",
    },
    output: "plant-based pepperoni/ vegan ",
    secondary_language:
      "real cauliflower thin pizza crust - on a thin and deliciously crispy cauliflower crust made with Violife Mozzarella Cheese",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.013.png",
    name: {
      first: "Clo Clo",
      last: "",
    },
    output: "delectably vegan",
    secondary_language:
      "Meatless pepperoni, Meatless Italian, Spicy Meatless Carribean Pizza",
    company_link: "https://clocloveganfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Meal replacement",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.013.png",
    name: {
      first: "Clo Clo",
      last: "",
    },
    output: "delectably vegan",
    secondary_language:
      "Meatless pepperoni, Meatless Italian, Spicy Meatless Carribean Pizza",
    company_link: "https://clocloveganfoods.com/",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.014.png",
    name: {
      first: "Avoca'Do",
      last: "",
    },
    output: "Plant-Based Pudding",
    secondary_language: "Rich and Dark Chocolate Flavor",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.016.png",
    name: {
      first: "OHi",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Coconut Macadamia/ No Grain, Gluten, or Soy/ Almond Curnch / Super Green / Almond Dark Chocolate",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.016.png",
    name: {
      first: "OHi",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Coconut Macadamia/ No Grain, Gluten, or Soy/ Almond Curnch / Super Green / Almond Dark Chocolate",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.016.png",
    name: {
      first: "OHi",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Coconut Macadamia/ No Grain, Gluten, or Soy/ Almond Curnch / Super Green / Almond Dark Chocolate",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.015.png",
    name: {
      first: "All Y'alls Food",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Black Pepper & Sea Salt / Prickly Pear Teriyaki / Prickly Pear Chipotle",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.015.png",
    name: {
      first: "All Y'alls Food",
      last: "",
    },
    output: " plant-based protein",
    secondary_language:
      "Black Pepper & Sea Salt / Prickly Pear Teriyaki / Prickly Pear Chipotle",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Snacks",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.017.png",
    name: {
      first: "Noops",
      last: "",
    },
    output: "oatmilk pudding / plant-based",
    secondary_language: "Vanilla/Caramel/Mocha/Chocolate Flavored",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Yogurts",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Yogurts",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Yogurts",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Millenials",
    state: "Yogurts",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Yogurts",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.018.png",
    name: {
      first: "Oatly Oatgurt",
      last: "",
    },
    output: "non-dairy full-fat yogurt alternative",
    secondary_language: "peach / black cherry / strawberry oatgurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Kids",
    state: "Yogurts",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.019.png",
    name: {
      first: "Kite Hill",
      last: "",
    },
    output: "dairy free",
    secondary_language:
      "plain / vanilla / peach / strawberry / blueberry almondmilk yogurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Yogurts",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.019.png",
    name: {
      first: "Kite Hill",
      last: "",
    },
    output: "dairy free",
    secondary_language:
      "plain / vanilla / peach / strawberry / blueberry almondmilk yogurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Yogurts",
    rank: "Flexitarian",
    time: "Convenience",
    photo: "plant_images.020.png",
    name: {
      first: "Kite Brytlife",
      last: "",
    },
    output: "plant-based yogurt",
    secondary_language:
      "plain / vanilla / blueberry lemon / tart cherry delicious, all-natural plant-based yogurt",
    company_link: "",
  },
  {
    _id: "5f9192b677e9f4026e5908ce",
    speciality: "Gen Z",
    state: "Yogurts",
    rank: "Vegan",
    time: "Convenience",
    photo: "plant_images.020.png",
    name: {
      first: "Kite Brytlife",
      last: "",
    },
    output: "plant-based yogurt",
    secondary_language:
      "plain / vanilla / blueberry lemon / tart cherry delicious, all-natural plant-based yogurt",
    company_link: "",
  },
];
